### ISSUE TITLE
Doesn't seem to work on IOB bank website anymore

### ISSUE THREAD

**Issue by thangarajj** [aaronraimist/DontFuckWithPaste#13]
The username & password field on this login form (and other forms on this banking site) block copy & paste:
https://www.iobnet.co.in/ibanking/login.do
Earlier this extension solves this issue, but not anymore. Tried in edge & firefox to same result.

Thanks for a great extension, it has helped me in other dumb websites.

**Comment by aaronraimist** [comment]
Hmm. I can't reproduce that. It doesn't appear to block copy or paste for me. I don't even need to activate the extension.

**Comment by navinthomas** [comment]
@aaronraimist Would you please check again? It definitely doesn't work for me as of today. I am using it on Firefox.

**Comment by aaronraimist** [comment]
@navinthomas did you activate the extension on that website? You need to go to the website, click on the icon for the extension, and then click save.

Just tried it again. The website blocks paste and then when I activate the extension it works fine for me.

**Comment by navinthomas** [comment]
@aaronraimist Yes, I did activate the extension on that website prior to testing. The extension is definitely activated on the page. I cannot paste anything into the Login ID and Password fields. Can you tell me which browser you are using?

**Comment by navinthomas** [comment]
Right now, I was able to paste in the fields by doing _Shift + Right Click_ on the fields and then clicking _Paste_. The normal _Ctrl + V_ shortcut does not paste anything. So, the site is blocking the paste shortcut too? Have you seen this before?

**Comment by aaronraimist** [comment]
I am using Firefox 95.0.2

**Comment by navinthomas** [comment]
I am also using Firefox 95.0.2

@aaronraimist Are you able to paste directly into those fields using _Ctrl + V_ (Windows/Linux shortcut for paste)?

**Comment by aaronraimist** [comment]
I'm on a Mac so I'm using Command + V but yes.
