### ISSUE TITLE
Broken website

### ISSUE THREAD

**Issue by raffaelemancuso** [aaronraimist/DontFuckWithPaste#19]
Does this extension work on [this website](https://faculti.net/receiving-external-equity-following-successfully-crowdfunded-technological-projects/)?

**Comment by aaronraimist** [comment]
What field are you having trouble pasting into? I went to the login and registration pages and I was able to paste into all the fields even without activating the extension.

**Comment by raffaelemancuso** [comment]
Oh sorry.
You are right.
Nevermind.
