### ISSUE TITLE
Doesn't work on manuscript central

### ISSUE THREAD

**Issue by raffaelemancuso** [aaronraimist/DontFuckWithPaste#20]
This extension doesn't seem to have an effect on the "E-mail" field of the registration form on [this website](https://mc.manuscriptcentral.com/ciai)

**Comment by aaronraimist** [comment]
On the create an account page? It works for me. Make sure you activate the extension by clicking the icon and then clicking the save button.

**Comment by raffaelemancuso** [comment]
Yes it works. Sorry
