### ISSUE TITLE
Issue with pasting into fb chat window

### ISSUE THREAD

**Issue by Will2knz** [aaronraimist/DontFuckWithPaste#3]
With the current version 2.31 for firefox.  When i go to past into a fb chat window with don't fuck past enable  it closer the window and i have to refresh the page to get the chat windows back up.

**Comment by aaronraimist** [comment]
Yes I can reproduce this but the whole point of v2.3 is now you can disable DFWP on sites that don't need it. Is there some reason you need DFWP to be active on Facebook? I wasn't aware that they blocked paste anywhere.

**Comment by Will2knz** [comment]
Sorry for the slow reply. No I have reason for DFWP on facebook. How do I disable DFWP per sites

**Comment by aaronraimist** [comment]
Click on the DFWP toolbar icon when you are on Facebook and then click the X next to any rules that are listed there. Then the icon should say inactive if you hover over it.

You may need to put DFWP back in the toolbar or overflow menu if you got rid of it when 2.3 came out.

**Comment by Will2knz** [comment]
I follow the instructions you give with no change to the issue. I have fixed the issue now by going to the firfox extensions file and deleted the DFWP.xpi file and then reinstalling DFWP. 

thanks for you help.

Richard
