### ISSUE TITLE
Screenshots of the UI of Don't Fuck With Paste for addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [aaronraimist/DontFuckWithPaste#5]
There's the screenshot away at <https://jsfiddle.net/aaronraimist/6qrnwcjp/28/show/>, it might be more user-friendly, for newcomers, to have a screenshot at the home page on AMO. 

![2018-06-01 20 16 06 35 dorothy ashby - theme from the valley of dolls - youtube](https://user-images.githubusercontent.com/192271/40859430-b6c031a6-65d9-11e8-895f-1784152fbc24.png)

![2018-06-01 20 16 30 35 dorothy ashby - theme from the valley of dolls - youtube](https://user-images.githubusercontent.com/192271/40859438-bf164d04-65d9-11e8-88ec-354a10cc2208.png)

Scary, huh? I'm sure that you can do better :-)

**Comment by aaronraimist** [comment]
👍 Thanks for the suggestion. I must've just forgotten that I could add screenshots to AMO. For now I just added that old one to AMO.
