### ISSUE TITLE
mutualpaypropertypay.com still breaks paste in Firefox

### ISSUE THREAD

**Issue by ahelwer** [aaronraimist/DontFuckWithPaste#6]
[HOAPass Member.zip](https://github.com/aaronraimist/DontFuckWithPaste/files/2734802/HOAPass.Member.zip)

I've added a rule and the extension lights up blue in the top bar. Unfortunately, pasting is still disabled; I've attached the page source.

**Comment by aaronraimist** [comment]
Do you experience the issue if you just open at .html file? Seems to work fine for me even without the extension enabled, I assume the part of the source code that blocks pasting isn't included.

Would you mind testing on Chrome as well? If it is also broken on Chrome then can you please file an issue here https://github.com/jswanner/DontFuckWithPaste/issues?
